---
- hosts: localhost
  gather_facts: false
  become: true
  become_method: sudo
  become_user: root

  tasks:

  - name: apt update
    command: apt -y update
    register: out

  - name: Install list
    apt: "name={{item}} state=latest"
    with_items:
            - curl
            - nano
            - docker
            - docker-compose
            - git
            - ansible
    register: out

  - name: CleanUP application directory
    file:
      path: /app/
      state: absent
    register: out

  - name: Create catalog
    file:
      path: /app/
      state: directory
    register: out

  - name: Git clone
    git:
      repo: 'https://okostiukromexsoft:F,f,fufkfvfuf321@github.com/okostiukromexsoft/Docker_internal.git'
      dest: /app
      clone: yes
      update: yes
    register: out

  - name: Run docker build
    shell: |
      cd /app/prod &&
      docker-compose build
    register: out

  - debug: msg="{{ out.stdout }}"
  - debug: msg="{{ out.stdout }}"