---
- hosts: localhost
  gather_facts: false
  become: true
  become_method: sudo
  become_user: root

  tasks:

  - name: apt update
    command: apt -y update

  - name: Install list
    apt: "name={{item}} state=latest"
    with_items:
            - curl
            - nano
            - docker
            - docker-compose
            - git
            - ansible
  - name: ClenUP application directory
    file:
      path: /app/
      state: absent

  - name: create catalog
    file:
      path: /app/
      state: directory

  - name: Git clone
    git:
      repo: 'https://okostiukromexsoft:F,f,fufkfvfuf321@github.com/okostiukromexsoft/Docker_internal.git'
      dest: /app
      clone: yes
      update: yes

  - name: Run docker build
    shell: |
      cd /app/prod &&
      docker-compose build