---
- hosts: all
  gather_facts: false
  become: true
  become_method: sudo
  become_user: root
  become_flags: '-s /bin/bash'

  tasks:

  - name: apt update
    command: apt -y update

  - name: Install list
    apt: "name={{item}} state=latest"
    with_items:
            - curl
            - nano
            - docker
            - docker-compose
            - git
            - ansible
  - name: ClenUP application directory
    shell: rm -rf /app
    warn: False

  - name: create catalog
    command: mkdir /app
    warn: False

  - name: Git clone
    git:
      repo: 'https://okostiukromexsoft:F,f,fufkfvfuf321@github.com/okostiukromexsoft/Docker_internal.git'
      dest: /app
      clone: yes
      update: yes

  - name: Run docker build
    shell: |
      cd /app/prod &&
      docker-compose build