version: '2.1'
services:
   db:
     build:
      context: .
      args:
       MYSQL_ROOT_PASSWORD: Start753
       DB_NAME: wordpress
       DB_USER: wordpress
       DB_PASS: wordpress
       MYSQL_CHARSET: utf8
       MYSQL_COLLATION: utf8_general_ci
       MYSQL_DATA_DIR: /var/lib/mysql
       MYSQL_RUN_DIR: /var/run/mysqld
       MYSQL_LOG_DIR: /var/log/mysql
       MYSQL_USER: mysql
       ZABBIX_SERVER: 10.0.0.42
     container_name: db0
     volumes:
       - db_data:/var/lib/mysql
       - ./src/var/log/db0:/var/log/mysql
     restart: always

   wordpress_first_server:
     depends_on:
       - db
     image: wordpress:latest
     container_name: www0
     ports:
       - "8081:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     volumes:
       - ./src/var/www/www0:/var/www/html
       - ./src/var/log/www0:/var/log/apache2

   wordpress_second_server:
     depends_on:
       - db
       - wordpress_first_server
     image: wordpress:latest
     container_name: www1
     ports:
       - "8082:80"
     restart: always
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
     volumes:
       - ./src/var/www/www1:/var/www/html
       - ./src/var/log/www1:/var/log/apache2

   web_server_reverse_proxy:
     depends_on:
       - db
       - wordpress_first_server
       - wordpress_second_server
     image: nginx:latest
     container_name: wwwproxy0
     ports:
       - "80:80"
     restart: always
     volumes:
       - ./src/etc/nginx/:/etc/nginx/
       - ./src/var/log/nginx:/var/log/nginx

   redis_server:
      build:
         context: ./redis/.
         args:
           ZABBIX_SERVER: 10.0.0.42
      container_name: redis
      ports:
       - "6379:6379"
      restart: always
      volumes:
       - ./src/var/log/redis:/var/log/redis
       - ./src/redis:/app

volumes:
  db_data:
